Readme updates, better env var support

diff --git a/dotfiller b/dotfiller
--- a/dotfiller
+++ b/dotfiller
@@ -12,7 +12,7 @@ DOTFILLER_GIT_CONFIGURED="${DOTFILLER_HOME}/git_configured"
 DOTFILLER_SYNC_FROM="${DOTFILLER_HOME}/dropbox_dir"
 DOTFILLER_SYNC_TO="${DOTFILLER_HOME}/git_dir"
 DOTFILLER_SYNC_LOG="${DOTFILLER_HOME}/sync.log"
-SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
+SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/${0#"./"}"
 dropbox=$DOTFILLER_HOME/bin/dropbox
 alias dropbox=$dropbox
 
@@ -29,6 +29,10 @@ VIOLET="\\033[1;35m"
 WHITE="\\033[1;37m"
 YELLOW="\\033[1;33m"
 MAGENTA="\\033[1;31m"
+
+if [ ! -z "$OVERWRITE_ALL_FOREVER" ]; then
+    touch "$OVERWRITE_FOREVER_FILE"
+fi
 
 function _in_array() {
     local needle="$1" item
@@ -47,7 +51,7 @@ function _shouldWeLink() {
     declare -a overwrites
     if [ -f "$OVERWRITES_FILE" ]; then readarray -t overwrites < "$OVERWRITES_FILE"; fi
     if _in_array "$file" "overwrites"; then return 0; fi
-    if [ ! -z "$overwrite_all" ]; then
+    if [ ! -z "$OVERWRITE_ALL" ]; then
         echo "Adding $file to $OVERWRITES_FILE"
         echo "$file" >> "$OVERWRITES_FILE"
         return 0
@@ -64,7 +68,7 @@ function _shouldWeLink() {
             return 0
         fi
         if [[ "$overwriteResponse" =~ ^[Ee]$ ]]; then
-            overwrite_all=1
+            OVERWRITE_ALL=1
             echo "Adding $file to $OVERWRITES_FILE"
             echo "$file" >> "$OVERWRITES_FILE"
             return 0
@@ -74,6 +78,7 @@ function _shouldWeLink() {
             return 0
         fi
     else
+
         echo "$(date)- $file does not appear in $OVERWRITES_FILE, so we are not overwriting. Run \"$SCRIPTPATH links\" to interactively add overwrites." >> DOTFILLER_UNATTENDED_LOGS
     fi
     return 1
@@ -124,13 +129,13 @@ function links() {
 function provider_sync_init() {
     rm "$DOTFILLER_SYNC_LOG" 2> /dev/null
     echo -e "Running a sync now..."
-    sync
+    sync 1
     echo -e "${YELLOW}"
     cat "$DOTFILLER_SYNC_LOG"
     echo -e "${BLUE}\nDoes the above log look correct for a sync?${C}"
-    read -p "(y/n)? " -n 1 -r provider_sync_successful
+    _question "PROVIDER_SYNC_SUCCESSFUL" "(y/n)? " 1
     echo
-    if [[ ! "$provider_sync_successful" =~ ^[Yy]$ ]]; then
+    if [[ ! "$PROVIDER_SYNC_SUCCESSFUL" =~ ^[Yy]$ ]]; then
         echo -e "${RED}ERROR${C}: Sync was not successful. Exiting as we have no way to fix that :("
     fi
     echo
@@ -138,29 +143,40 @@ function provider_sync_init() {
     echo
     echo -e "${BLUE}Cron${C}: This method will add a line to your ${YELLOW}crontab${C} to automatically sync and commit changes every hour, if there are any."
     echo -e "${BLUE}Manual${C}: This method will require you to run the ${YELLOW}sync${C} command manually to update the repo."
-    PS3='Choose: '
-    #types=("Login" "Detected Changes" "Manual")
-    types=("Cron" "Manual")
-    select type in "${types[@]}"; do
-        case $type in
-            "Cron")
-                DOTFILLER_SYNC_COMMAND="0 0-23 * * * $SCRIPTPATH sync"
-                echo -e "Adding the following line to your ${YELLOW}crontab${C}: ${GREEN}${DOTFILLER_SYNC_COMMAND}${C}"
-                ! (crontab -l | grep -q "$DOTFILLER_SYNC_COMMAND") && (crontab -l; echo "$DOTFILLER_SYNC_COMMAND") | crontab -
-                break
-                ;;
-            # "Regular")
-            #     TODO
-            #     break
-            #     ;;
-            "Manual")
-                echo -e "Okay! Just run ${GREEN}${SCRIPTPATH} sync${C} whenever you need to sync from Dropbox to Git."
-                break
-                ;;
-            *) echo -e "Invalid option ${RED}${REPLY}${C}";;
-        esac
-    done
+    if [ -z "$SYNC_CHOICE" ]; then
+        PS3='Choose: '
+        select type in Cron Manual; do
+            case $type in
+                "Cron")
+                    sync_choice_cron
+                    break
+                    ;;
+                # "Regular")
+                #     TODO
+                #     break
+                #     ;;
+                "Manual")
+                    sync_choice_manual
+                    break
+                    ;;
+                *) echo -e "Invalid option ${RED}${REPLY}${C}";;
+            esac
+        done
+    else
+        echo "$SYNC_CHOICE (Set by env)"
+        "sync_choice_$SYNC_CHOICE"
+    fi
     touch "$DOTFILLER_SYNC_CONFIGURED"
+}
+
+function sync_choice_cron() {
+    DOTFILLER_SYNC_COMMAND="0 0-23 * * * $SCRIPTPATH sync"
+    echo -e "Adding the following line to your ${YELLOW}crontab${C}: ${GREEN}${DOTFILLER_SYNC_COMMAND}${C}"
+    ! (crontab -l | grep -q "$DOTFILLER_SYNC_COMMAND") && (crontab -l; echo "$DOTFILLER_SYNC_COMMAND") | crontab -
+}
+
+function sync_choice_manual() {
+    echo -e "Okay! Just run ${GREEN}${SCRIPTPATH} sync${C} whenever you need to sync from Dropbox to Git."
 }
 
 # log if not interesting, otherwise echo
@@ -175,7 +191,7 @@ function logini() {
 }
 
 function sync() {
-    if [ ! -f "$DOTFILLER_SYNC_CONFIGURED" ]; then
+    if [ ! -f "$DOTFILLER_SYNC_CONFIGURED" ] && [ -z $1 ]; then
         echo "${RED}ERROR${C}: Sync hasn't been configured yet! Run ${YELLOW}${SCRIPTPATH} install${RED}.${C}"
         exit 1
     fi
@@ -204,7 +220,7 @@ function _update() {
 
 function git_init() {
     [[ "$(command -v git)" ]] || { echo -e "${RED}ERROR: ${C}You should probably install ${YELLOW}git${C} first." 1>&2 ; exit 1; }
-    read -p "Enter the URL to your dotfile git repository (This will be passed directly to git): " USER_GIT_REPO
+    _question "USER_GIT_REPO" "Enter the URL to your dotfile git repository (This will be passed directly to git) "
     echo
     if ! git clone "$USER_GIT_REPO" "$USER_REPO_STORE"; then
         echo -e "${RED}ERROR${C}: Git didn't seem to like that input."
@@ -221,31 +237,41 @@ function git_provider_install() {
     echo -e "${BLUE}Login${C}: This method will add a line to your ${YELLOW}~/.bashrc${C} (If it isn't already there) to automatically pull the repo on login."
     #echo -e "${BLUE}Regular${C}: This method will add a crontab to regularly check for new updates to the repo."
     echo -e "${Blue}Manual${C}: This method will require you to run the ${YELLOW}update${C} command manually to update the repo."
-    PS3='Choose: '
-    #types=("Login" "Detected Changes" "Manual")
-    types=("Login" "Manual")
-    select type in "${types[@]}"; do
-        case $type in
-            "Login")
-                DOTFILLER_BASHRC_UPDATE_GIT="$SCRIPTPATH update"
-                echo -e "Adding the following line to your ${YELLOW}~/.bashrc${C}: ${GREEN}${DOTFILLER_BASHRC_UPDATE_GIT}${C}"
-                /bin/grep "${DOTFILLER_BASHRC_UPDATE_GIT}" "$HOME/.bashrc" > /dev/null || echo "${DOTFILLER_BASHRC_UPDATE_GIT}" >> "$HOME/.bashrc"
-                break
-                ;;
-            # "Regular")
-            #     TODO
-            #     break
-            #     ;;
-            "Manual")
-                echo -e "Okay! Just run ${GREEN}${SCRIPTPATH} update${C} whenever you need to update the repo."
-                break
-                ;;
-            *) echo -e "Invalid option ${RED}${REPLY}${C}";;
-        esac
-    done
-
+    if [ -z "$GIT_PROVIDER_UPDATE" ]; then
+        PS3='Choose: '
+        select type in Login Manual; do
+            case $type in
+                "Login")
+                    git_update_login
+                    break
+                    ;;
+                # "Regular")
+                #     TODO
+                #     break
+                #     ;;
+                "Manual")
+                    git_update_manual
+                    break
+                    ;;
+                *) echo -e "Invalid option ${RED}${REPLY}${C}";
+            esac
+        done
+    else
+        echo "$GIT_PROVIDER_UPDATE (Set by env)"
+        "git_update_$GIT_PROVIDER_UPDATE"
+    fi
     echo -e "${GREEN}Git setup complete.${C}"
     echo "$LINK_DIR" > "$DOTFILLER_LINK_DIR_CONFIG"
+}
+
+function git_update_login() {
+    DOTFILLER_BASHRC_UPDATE_GIT="$SCRIPTPATH update"
+    echo -e "Adding the following line to your ${YELLOW}~/.bashrc${C}: ${GREEN}${DOTFILLER_BASHRC_UPDATE_GIT}${C}"
+    /bin/grep "${DOTFILLER_BASHRC_UPDATE_GIT}" "$HOME/.bashrc" > /dev/null || echo "${DOTFILLER_BASHRC_UPDATE_GIT}" >> "$HOME/.bashrc"
+}
+
+function git_update_manual() {
+    echo -e "Okay! Just run ${GREEN}${SCRIPTPATH} update${C} whenever you need to update the repo."
 }
 
 function _question() {
@@ -253,7 +279,7 @@ function _question() {
     local question=$2
     local single_char=$3
     if [ -z "${!arg}" ]; then
-        local cmd="read -p ${question@Q}:"
+        local cmd="read -p ${question@Q}: "
         if [ ! -z "$single_char" ]; then
             cmd+="-n 1 "
         fi
@@ -340,7 +366,7 @@ function _provider_installed() {
     echo
     SYMLINK_NOW=${SYMLINK_NOW:-y}
     if [[ "$SYMLINK_NOW" =~ ^[Yy]$ ]]; then
-        links "$LINK_DIR"
+        links ${LINK_DIR:-"$(cat "$DOTFILLER_LINK_DIR_CONFIG")"}
         echo "We're finished symlinking."
     else
         echo "Okay!"
@@ -350,28 +376,39 @@ function _provider_installed() {
     echo -e "${BLUE}Login${C}: This method will add a line to your ${YELLOW}~/.bashrc${C} (If it isn't already there) to create symlinks for new files when you open a new shell."
     #echo -e "${BLUE}Detected Changes${C}: This method will add a line to your ${YELLOW}~/.bashrc${C} (If it isn't already there) that runs a daemon script to detect changes from your provider, and symlink new files found."
     echo -e "${BLUE}Manual${C}: This method will require you to run the ${YELLOW}create_links${C} script manually to add new symlinks."
-    PS3='Choose: '
-    #types=("Login" "Detected Changes" "Manual")
-    types=("Login" "Manual")
-    select type in "${types[@]}"; do
-        case $type in
-            "Login")
-                DOTFILLER_BASHRC_CREATE_LINKS="$SCRIPTPATH symlink_unattended"
-                echo -e "Adding the following line to your ${YELLOW}~/.bashrc${C}: ${GREEN}${DOTFILLER_BASHRC_CREATE_LINKS}${C}"
-                /bin/grep "${BASHRC_CREATE_LINKS}" "$HOME/.bashrc" > /dev/null || echo "${BASHRC_CREATE_LINKS}" >> "$HOME/.bashrc"
-                break
-                ;;
-            # "Detected Changes")
-            #     TODO
-            #     break
-            #     ;;
-            "Manual")
-                echo -e "Okay! Just run ${GREEN}${SCRIPTPATH} links${C} whenever you need to create new symlinks."
-                break
-                ;;
-            *) echo -e "Invalid option ${RED}${REPLY}${C}";;
-        esac
-    done
+    if [ -z "$CREATE_LINKS_WHEN" ]; then
+        PS3='Choose: '
+        select type in Login Manual; do
+            case $type in
+                "Login")
+                    create_links_login
+                    break
+                    ;;
+                # "Detected Changes")
+                #     TODO
+                #     break
+                #     ;;
+                "Manual")
+                    create_links_manual
+                    break
+                    ;;
+                *) echo -e "Invalid option ${RED}${REPLY}${C}";;
+            esac
+        done
+    else
+        echo "$CREATE_LINKS_WHEN (Set by env)"
+        "create_links_$CREATE_LINKS_WHEN"
+    fi
+}
+
+function create_links_login() {
+    DOTFILLER_BASHRC_CREATE_LINKS="$SCRIPTPATH symlink_unattended"
+    echo -e "Adding the following line to your ${YELLOW}~/.bashrc${C}: ${GREEN}${DOTFILLER_BASHRC_CREATE_LINKS}${C}"
+    /bin/grep "${DOTFILLER_BASHRC_CREATE_LINKS}" "$HOME/.bashrc" > /dev/null || echo -e "\n${DOTFILLER_BASHRC_CREATE_LINKS}\n" >> "$HOME/.bashrc"
+}
+
+function create_links_manual() {
+    echo -e "Okay! Just run ${GREEN}${SCRIPTPATH} links${C} whenever you need to create new symlinks."
 }
 
 function install() {
@@ -383,59 +420,77 @@ function install() {
 
     mkdir -p "$DOTFILLER_HOME"
 
-    PS3='Pick your installation type: '
-    types=("Dropbox" "Git" "Sync" "Quit")
-    select type in "${types[@]}"; do
-        case $type in
-            "Dropbox")
-                echo -e "Dropbox installation type selected, beginning config..."
-                install_type=Dropbox
-                dropbox_init
-                dropbox_provider_install
-                _provider_installed
-                break
-                ;;
-            "Git")
-                echo -e "Git installation type selected, beginning config..."
-                install_type=Git
-                git_init
-                git_provider_install
-                _provider_installed
-                break
-                ;;
-            "Sync")
-                echo -e "Sync installation type selected, beginning config..."
-                install_type=Sync
-                if [ ! -f "$DOTFILLER_DROPBOX_CONFIGURED" ]; then
-                    echo -e "${BLUE}Dropbox${C} has not yet been configured, starting config now..."
-                    dropbox_init
-                fi
-                if [ ! -f "$DOTFILLER_GIT_CONFIGURED" ]; then
-                    echo -e "${BLUE}Git${C} has not yet been configured, starting config now..."
-                    git_init
-                fi
-                provider_sync_init
-                break
-                ;;
-            "Quit")
-                echo -e "Bye!"
-                exit
-                ;;
-            *) echo -e "Invalid option ${RED}${REPLY}${C}";;
-        esac
-    done
+    if [ -z "$INSTALL_TYPE" ]; then 
+        PS3='Pick your installation type: '
+        types=("Dropbox" "Git" "Sync" "Quit")
+        select type in "${types[@]}"; do
+            case $type in
+                "Dropbox")
+                    install_type_dropbox
+                    break
+                    ;;
+                "Git")
+                    install_type_git
+                    break
+                    ;;
+                "Sync")
+                    install_type_sync
+                    break
+                    ;;
+                "Quit")
+                    echo -e "Bye!"
+                    exit
+                    ;;
+                *) echo -e "Invalid option ${RED}${REPLY}${C}";;
+            esac
+        done
+    else
+        echo "$INSTALL_TYPE (Set by env)"
+        "install_type_$INSTALL_TYPE"
+    fi
     echo
     echo -e "All ${GREEN}done${C}."
+}
+
+function install_type_dropbox() {
+    echo -e "Dropbox installation type selected, beginning config..."
+    install_type=Dropbox
+    dropbox_init
+    dropbox_provider_install
+    _provider_installed
+}
+
+function install_type_git() {
+    echo -e "Git installation type selected, beginning config..."
+    install_type=Git
+    git_init
+    git_provider_install
+    _provider_installed
+}
+
+function install_type_sync() {
+    echo -e "Sync installation type selected, beginning config..."
+    install_type=Sync
+    if [ ! -f "$DOTFILLER_DROPBOX_CONFIGURED" ]; then
+        echo -e "${BLUE}Dropbox${C} has not yet been configured, starting config now..."
+        dropbox_init
+    fi
+    if [ ! -f "$DOTFILLER_GIT_CONFIGURED" ]; then
+        echo -e "${BLUE}Git${C} has not yet been configured, starting config now..."
+        git_init
+    fi
+    provider_sync_init
 }
 
 function help() {
     echo -e "Welcome to Dotfiller, yet another Dotfile manager. You must pass an argument to use this script. I suggest ${GREEN}$0 install${C} .
 Available arguments:
-       ${YELLOW}install${C} - Will guide you through installing Dotfiller with a provider
-       ${YELLOW}   link${C} - Will link files from your provider to your home directory, asking questions if it needs to overwrite anything
-${YELLOW}symlink_unattended - Above, but won't ask you questions
-            ${YELLOW}update - Pulls from a remote Git provider
-              ${YELLOW}sync - Copies from Dropbox to Git, then commits any changes.
+        ${YELLOW}install${C} - Will guide you through installing Dotfiller with a provider
+        ${YELLOW}   link${C} - Will link files from your provider to your home directory, asking questions if it needs to overwrite anything
+ ${YELLOW}symlink_unattended - Above, but won't ask you questions, outputs to log ~/.dotfiller/unattended.log
+             ${YELLOW}update - Pulls from a remote Git provider
+               ${YELLOW}sync - Copies from Dropbox to Git, then commits any changes.
+${YELLOW}_provider_installed - Runs the 'Set up automatic symlinking' prompt
 
 Visit ${ORANGE}https://github.com/Makeshift/Dotfiller${C} for updates and issues.
     "
